### PR TITLE
Upgrade engine and add webpack

### PR DESCRIPTION
**Pull request by barnuri**

### CODE REVIEW

**Comment by barnuri** [comment]
add also a prettier so its look like a lot of changes

**Comment by barnuri** [comment]
also you have here git hooks to incress version & github actions to publish the extension
you just need to add secret to you repo named VSCE_PAT

**Comment by barnuri** [comment]
@hsen-dev

**Review by hsen-dev — COMMENTED** [review]
What is this?

**Comment by barnuri** [comment]
@hsen-dev 
upgrade the extension engine & dependencies because it was too old
also and webpack to speed up the extension 
and prettier for save to code format for all files
and github actions to publish it every time you push to master
also anding missing types and make tsconfig to be strict
your extenstion is very useful but very old

**Comment by barnuri** [comment]
dont forget to update the repo secrets, you need to set a new secret named VSCE_PAT with a the token for publishing the extension

**Comment by barnuri** [comment]
@hsen-dev

**Pull request merged**
